import math


def hardness_value_calculation(tds_value, harness_calibration_value):
    if tds_value != 0:
        hardness_result = tds_value + float(harness_calibration_value)
        hardness_round_result = round(hardness_result, 2)
        return hardness_round_result
    else:
        print("bad hardness")

def do_value_calculation(temperature_round_result, ammonia_round_result, do_calibration_value):
    # atm_pressure = 1.5
    # # print("line 359", atm_pressure, temperature_round_result, ammonia_round_result)
    # kh = ((4.34 * 10 ** 4) / 25) * temperature_round_result
    # po2 = atm_pressure
    # xo2 = po2 / kh
    # nHo2 = 1000 / (93.44 + ammonia_round_result)
    # nO2 = xo2 * nHo2
    # no2_derived = nO2 * 15.59 * 1000
    # do_round_result = round(no2_derived, 2) + float(do_calibration_value)
    # print("line 366", do_round_result)  # 5 to 10 ppm normal
    # if 4 <= do_round_result <= 6:
    #     return do_round_result
    # else:
    #     print("invalid do")
    #     return do_round_result
    do_result = ((8.4 * temperature_round_result) / 25) - 0.2
    do_round_result = round(do_result, 2)
    print(do_round_result)
    return do_round_result

def ammonia_value_calculation(ph_round_result, temp_round_result):
    pH_val = ph_round_result
    temp_val = temp_round_result
    pKa = 0.09018 + 2727.92 / (temp_val + 273.15)
    ammonia = 1 / (10 ** (pKa - pH_val) + 1)
    ammonia_round_result = round(ammonia, 5)
    return ammonia_round_result


def temperature_value_calculation(temperature_value, temperature_calibration_value=0):
    # temperature equation for D8020ND-1.0
    
    calibration_val = float(temperature_calibration_value)
    RTO = 10000  # Ω
    B = 3900  # K
    VCC = 5  # Supply voltage
    R = 10000  # R=10KΩ
    T0 = 25 + 273.15
    VRT = (5.00 / 1023.00) * (temperature_value + calibration_val)  # Conversion to voltage
    VR = VCC - VRT
    RT = VRT / (VR / R)  # Resistance of RT

    ln = math.log(RT / RTO)
    TX = (1 / ((ln / B) + (1 / T0)))  # Temperature from thermistor

    TX = TX - 273.15  # Conversion to Celsius

    temp_round_result = round(TX, 5)
    return temp_round_result

        
def tds_value_calculation(tds_value, tds_calibrations_value=0):
    
    
    tds_value = (895 - tds_value) * 67 / 300
    # tds_volt = tds_value * 5 / 1024
    # tds_result = (tds_volt * 2.5 / 1000)
    # tds_round_result = round(tds_result, 5)
    # print(tds_round_result)
    temperature = 25
    calibration = float(tds_calibrations_value)
    analog_volts = tds_value * 5 / 1024
    compensationCoefficient = 1.0 + 0.02 * (temperature - 25.0)
    compensationVolatge = analog_volts / compensationCoefficient
    tds = (133.42 * compensationVolatge ** 3 - 255.86 * compensationVolatge ** 2 + 857.39 * compensationVolatge) * calibration
    tds_round_result = round(tds, 5)
    return tds_round_result

        
def ph_value_calculation(ph_value, ph_calibration_value=0):
    ph_round_result = 0.00
    calibration_val = float(ph_calibration_value)
    pH_volts = ph_value * 5 / 1024
    ph = -5.7 * pH_volts + 21.34 + calibration_val
    ph_round_result = round(ph, 5)

        
def alkalinity_value_calculation():
    error_value = 99.99
    return 99.99

def analogToPH(analog, calibration = 0):
    '''
    This equation is generated by two point calibration.
    The details of this equation can be found in hardware documetation
    '''
    R1 = 10 # 10k ohm
    R2 = 22 # 22k ohm
    Aref = 3.3  # Analog reference voltage
    b = 10  # Analog Resolution bits
    test_pH = 7.1   # pH value tested
    test_pH_terminal_voltage = 2.52 # Voltage at the TLC4502C output
    m = 2.4/0.28    # Comes from two point calibration
    
    pH = m * (test_pH_terminal_voltage - analog * ((R1 + R2)/R2) * (Aref/(2**b - 1))) + test_pH + calibration
    return pH

def analogToTemperature(analog, calibration = 73):
    import math
    RTO = 10000  # Ω
    B = 3900  # K
    VCC = 5  # Supply voltage
    R = 10000  # R=10KΩ
    T0 = 25 + 273.15
    
    R1 = 10 #divider
    R2 = 22 #divider
    Aref = 3.3
    b = 10 #reolution
    
    analog = analog * Aref/5 * (R1 + R2)/R2
    
    VRT = (analog + calibration) * VCC / (2**b - 1) # Conversion to voltage
    VR = VCC - VRT
    RT = VRT / (VR / R)  # Resistance of RT
    
    ln = math.log(RT / RTO)
    temperature_kelvin = (1 / ((ln / B) + (1 / T0)))  # Temperature from thermistor

    temperature_celsiuus = temperature_kelvin - 273.15  # Conversion to Celsius
    
    return temperature_celsiuus

# def analogToTDS(analog, calibration = 20, temperature = 25):
#     x = (1023 - analog)*3.3
#     averageVoltage = x*3.3/1023*32/22
#     compensationCoefficient = 1.0+0.02*(temperature-25.0)
#     compensationVoltage = averageVoltage/compensationCoefficient
#     tds = (133.42*compensationVoltage*3 - 255.86*compensationVoltage*2 + 857.39*compensationVoltage)/(2*calibration)
#     return tds

def analogToTDS(analog, calibration = 20, temperature = 25, analog_const:int=1023):
    x = (analog_const - analog)*3.3
    averageVoltage = x*3.3/1023*32/22
    compensationCoefficient = 1.0+0.02*(temperature-25.0)
    compensationVoltage = averageVoltage/compensationCoefficient
    tds = (133.42*compensationVoltage**3 - 255.86*compensationVoltage**2 + 857.39*compensationVoltage)/(2*calibration)
    return tds


def get_battery_voltage(analog_reading):
    VOLTAGE_REFERENCE = 3.3
    R1 = 10 * 1000
    R5 = 10 * 1000
    ERROR_VOLTAGE = 0

    gpio_voltage = (float(analog_reading) / 1023) * VOLTAGE_REFERENCE
    battery_voltage = ((R1 + R5) / R5) * (gpio_voltage + ERROR_VOLTAGE)

    return round(battery_voltage,2)

def get_solar_voltage(analog_reading):
    VOLTAGE_REFERENCE = 3.3
    R4 = 33 * 1000
    R6 = 22 * 1000
    ERROR_VOLTAGE = 0

    gpio_voltage = (float(analog_reading) / 1023) * VOLTAGE_REFERENCE
    solar_voltage = ((R4 + R6) / R6) * (gpio_voltage + ERROR_VOLTAGE)

    return round(solar_voltage,2)
